export interface GameConstantsI {
  MIN_RANGED_ATTACK_RADIUS_SQUARED: number // 16
  MAX_RANGED_ATTACK_RADIUS_SQUARED: number // 49
  MAX_MAGIC_ATTACK_RADIUS_SQUARED: number // 25
  MAGIC_ATTACK_SPLASH_PERCENTAGE: number // .75
  MAX_MELEE_ATTACK_RADIUS_SQUARED: number // 2
  SENSE_EXIT_THRESHOLD: number // 144
  PLAYER_MOVE_DELAY: number // 2
  PLAYER_HEAL_POWER: number // 10
  PLAYER_HEAL_DELAY: number // 20
  PLAYER_MELEE_POWER: number // 20
  PLAYER_MELEE_DELAY: number // 2
  PLAYER_MAGIC_POWER: number // 8
  PLAYER_MAGIC_DELAY: number // 4
  PLAYER_RANGED_POWER: number // 18
  PLAYER_RANGED_DELAY: number // 3
}
